### ISSUE TITLE
Proposal Review

### ISSUE THREAD

**Issue by Eroatus** [ASU-CompMethodsPhysics-PHY494/final-2018-494_heat_wizards#1]
We updated our proposal and pushed the PDF. @orbeckst please review it at your leisure, and thanks in advance!

**Comment by orbeckst** [comment]
@ASU-CompMethodsPhysics-PHY494/494_heat_wizards overall the proposal looks good. 

1. However, you have not specified how you are going to consider the external temperature as boundary conditions. I suggest that you look at the temperature over a typical 48h period in summer and winter (instead of "for a fixed number of time steps" as specified vaguely in Objective 3). One reason to work with the heat equation is that you can easily include externally varying boundary conditions such as a sinusoidally varying temperature (just find typical min/max data for Phoenix).
2. I would add as a 0th objective to prototype with the 1D case – this will already provide you with insights in the behavior of materials and thickness; you can do some of your parameter scans (Objective 3) with the 1D problem and then use 2D where it counts, namely when you vary shapes and combine multiple materials such as walls and windows. I would not try to do exhaustive parameter scans, just demonstrate in a few cases that you can study different parameters.
3. The stretch goals look fine to me.
4. Say somewhere that you will visualize the temperature distribution – in 1D you can plot T(x, t), in 2D you can plot, quite literally, heatmaps T(x, y) for a fixed time point t. 
5. (EDIT) @Eroatus please make sure that all other team members' names are also on the proposal.

**Comment by orbeckst** [comment]
Once you have addressed my points in https://github.com/ASU-CompMethodsPhysics-PHY494/final-2018-494_heat_wizards/issues/1#issuecomment-381390806 please leave a comment here and I will review again.

**Comment by orbeckst** [comment]
Note that the 1-page page limit is a soft limit; if you need more space then that's fine. Rather be precise and go over the page than to cut corners. The Proposal should be the document that guides the overall directions of your project.

**Comment by Eroatus** [comment]
Good morning @orbeckst. The updated version of the proposal has been pushed. Thanks for mentioning that the page limit is a soft limit, otherwise the edits might have taken notably longer.

On another note, the other team members should be joining the team sometime today. Marko will be working until evening, but he will join right after and Zhichao will probably join once he sees the message I left them.

**Comment by orbeckst** [comment]
Thanks for the quick response.

Excellent idea to add the team name to the proposal. The objectives are well formulated.

## Minor comments
- If you have time-varying boundary conditions then you will not arrive at a equilibrium solution. If you have fixed temperature and no AC inside then the equilibrium solution is same temperature inside and outside. If you have fixed temperature inside then you can get a steady state solution and you could quantify the heat flux in or out of the house and relate it to the energy required to maintain the temperature.
- Changes of materials such as windows will not affect the boundary conditions themselves but just lead to having to solve the heat equation with a heterogeneous geometry. 

## Evaluation

I **approve your proposal**.

You are good to proceed with your project. You _may_ amend it to take the minor comments into account.
